### ISSUE TITLE
Rethink the website

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#1201]
Which pages do we want to continue and which do we want to remove? 
How about splitting main navigation in two navigations? Could make sense to split in a push and a pull navigation.

Example from @SusanDefacto 
![sketch-homepage](https://user-images.githubusercontent.com/16101007/41527444-76c292d6-72e7-11e8-8ec6-03b7286a35d7.jpg)

Live example: https://www.lindner-group.com/de_DE/
Not really nice but you'll get the idea.

**Comment by RonaldDijkstra** [comment]
~~Slider~~

**Comment by sn3p** [comment]
### Navigation

> I'm not to sure about the visual 'grouping' of Referenties/Branches and Partners, could come across as visually muddy for users of the website.

Agree, but I think we should break down and regroup the navigation (right now the main navigation has way too many links). For me it would make sense to somehow group **Producten, Diensten, Branches** (solution related). And maybe group **Klanten/Referenties/Testimonials, Partners, Jobs, ...** (about Defacto).

If we want dedicated pages for Branches, we could do something like:

- Defacto
  - In de zorg
  - Bij de overheid
  - In het bedrijfsleven

### Slider / highlight

I'm not a fan of sliders, but it's nice to have space for highlighting/feature content that we can update regularly. If we want to "rotate" more highlights we could do a slider that doesn't slide but has a more subtile transition and a visual/informative controls:

```
Next >
Visit us at NextLearning 2018
```

### Other thoughts

- We might want to keep a small introduction/slogan on what we do (e.g. Developing People since 1987). This helps welcoming new visitors.
- Do we want to showcase/list our products individually (CAPP, KPP, Agile)? Or will the Products link be the only entrance to for example CAPP?
- Maybe we should introduce a (more personal) "about us" section on the homepage? I think we should show more of ourselves: who we are and how we work. This should help prospects and applicants to get aquatinted with us.

**Comment by sn3p** [comment]
Not really relevant anymore, but here is a design I did back in 2013:

![www3](https://user-images.githubusercontent.com/935529/41644693-1f3d02ce-746f-11e8-86e5-53b82add8392.png)

**Comment by lennartdefacto** [comment]
Yeah I agree with the regrouping. As Ronald mentioned before, there could be a better push/pull distinction between the links we show our visitors. 

> If we want dedicated pages for Branches, we could do something like:
> 
> Defacto
> - In de zorg
> - Bij de overheid
> - In het bedrijfsleven

I like this setup, it makes sense for the user/viewer. 

> Do we want to showcase/list our products individually (CAPP, KPP, Agile)? Or will the Products link be the only entrance to for example CAPP?

I'm a bit torn about this, it makes sense to group this and present it as 'a complete ecosystem'. Maybe we should discuss this also with someone from Sales/Consultancy?

> Maybe we should introduce a (more personal) "about us" section on the homepage? I think we should show more of ourselves: who we are and how we work. This should help prospects and applicants to get aquatinted with us.

Currently working on writing a more personalized Employer Branding text for the 'About us' page.

**Comment by RonaldDijkstra** [comment]
> Do we want to showcase/list our products individually (CAPP, KPP, Agile)? Or will the Products link be the only entrance to for example CAPP?

At this point we do have a few different products. 

> I'm a bit torn about this, it makes sense to group this and present it as 'a complete ecosystem'. Maybe we should discuss this also with someone from Sales/Consultancy?

Not just the one from sales and consultancy, this is a fundamental decision for the future of our website. 
Let's discuss this in private.

**Comment by RonaldDijkstra** [comment]
First small step is removing the old CAPP LMS page, first in NL:

#1258

**Comment by RonaldDijkstra** [comment]
Because this is an issue which can't be resolved I'll close it. All things mentioned in this issue are to be planned in the near future.
