### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#192]
Because reasons: 
http://searchengineland.com/http-https-seos-guide-securing-website-246940

Includes LS landing pages and jobs.defacto.nl.

**Comment by fatboypunk** [comment]
I think the only option to do this is with cloudflare (for the github pages) or anything that works like cloudflare. I could enable this for the german sites, which gives other extra's like H2. but for the defacto.nl  i'm kinda pessemistic because it has to many dns options to just switch it over.

LS is a different story, which is hosted on Amazon, so it could use a 'real' https certificate. And i guess we  could switch it to cloudflare as well for H2 if we want to

**Comment by fatboypunk** [comment]
Since this could become a real problem now maybe switch the site to amazon as well and update that to https?

**Comment by RonaldDijkstra** [comment]
Sounds good. I want that. How do we do that?

**Comment by RonaldDijkstra** [comment]
I want to do this ASAP. :)

**Comment by RonaldDijkstra** [comment]
https://www.troyhunt.com/life-is-about-to-get-harder-for-websites-without-https/

**Comment by RonaldDijkstra** [comment]
https://www.defacto.nl 
https://en.defacto.nl

Thanks @tarzan

**Comment by RonaldDijkstra** [comment]
I am so happy to close this!
